"""initial migrate

Revision ID: 355142cc33c2
Revises: 
Create Date: 2021-03-16 20:04:50.795115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '355142cc33c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('blogs', sa.Column('blog', sa.String(length=255), nullable=False))
    op.add_column('blogs', sa.Column('posted', sa.DateTime(), nullable=True))
    op.alter_column('blogs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('blogs', 'postedDate')
    op.drop_column('blogs', 'body')
    op.add_column('comments', sa.Column('comments', sa.Text(), nullable=False))
    op.add_column('comments', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('comments', 'postedDate')
    op.drop_column('comments', 'comment')
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'image_file')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=155), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('image_file', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'pass_secure')
    op.drop_column('users', 'bio')
    op.add_column('comments', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('postedDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'title')
    op.drop_column('comments', 'comments')
    op.add_column('blogs', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('postedDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('blogs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('blogs', 'posted')
    op.drop_column('blogs', 'blog')
    op.drop_table('roles')
    # ### end Alembic commands ###
